name: lcl
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - apipkg=1.5=py_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py37h8f50634_1
  - async_generator=1.10=py_0
  - attrs=20.1.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - blinker=1.4=py37_0
  - boto=2.49.0=py37_0
  - boto3=1.9.66=py37_0
  - botocore=1.12.67=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.1.1=py_0
  - catalogue=1.0.0=py37_1
  - certifi=2021.5.30=py37h89c1867_0
  - cffi=1.14.2=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - configparser=5.0.0=py_0
  - contextlib2=0.6.0.post1=py_0
  - cryptography=3.0=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - cymem=2.0.3=py37he6710b0_0
  - cython-blis=0.4.1=py37h7b6447c_1
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docker-pycreds=0.4.0=py_0
  - docutils=0.16=py37_1
  - easydict=1.9=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - execnet=1.7.1=py_0
  - expat=2.2.9=he6710b0_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - gensim=3.8.0=py37h962f231_0
  - git=2.23.0=pl526hacde149_0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.8=py_0
  - glib=2.65.0=h3eb4bd4_0
  - google-api-core=1.22.2=py37_0
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-cloud-core=1.4.3=py_0
  - google-cloud-storage=1.32.0=py_0
  - google-crc32c=1.0.0=py37h7b6447c_0
  - google-resumable-media=1.1.0=py_1
  - googleapis-common-protos=1.52.0=py37_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.2=py_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - huggingface_hub=0.0.10=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.4=py37h43977f1_0
  - ipynb-py-convert=0.4.6=pyh9f0ad1d_0
  - ipython=7.18.1=py37hc6149b9_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py37_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.2=py37_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab_pygments=0.1.1=pyh9f0ad1d_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.18.2=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcrc32c=1.1.1=he6710b0_2
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0=hd408876_0
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - markdown=3.2.2=py37_0
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mistune=0.8.4=py37h8f50634_1001
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - mock=4.0.2=py37hc8dfbb8_0
  - more-itertools=8.5.0=py_0
  - multidict=4.7.6=py37h7b6447c_1
  - murmurhash=1.0.2=py37he6710b0_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.6=py37hc8dfbb8_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.0=py_1
  - ninja=1.10.0=py37hfd86e86_0
  - nltk=3.5=py_0
  - notebook=6.1.4=py37hc8dfbb8_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - nvidia-ml=7.352.0=py_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - pandas=1.1.1=py37he6710b0_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - path=15.0.0=py37hc8dfbb8_0
  - path.py=12.5.0=0
  - pathtools=0.1.2=py_1
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - plac=0.9.6=py37_1
  - plotly=4.10.0=py_0
  - pluggy=0.13.1=py37hc8dfbb8_2
  - preshed=3.0.2=py37he6710b0_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - promise=2.3=py37hc8dfbb8_1
  - prompt-toolkit=3.0.7=py_0
  - protobuf=3.13.0=py37hf484d3e_0
  - psutil=5.7.2=py37h8f50634_0
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - pytest=6.0.1=py37hc8dfbb8_0
  - pytest-shutil=1.7.0=py_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.2=py37hac76be4_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - regex=2020.7.14=py37h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - retrying=1.3.3=py37_2
  - rsa=4.6=py_0
  - s3transfer=0.1.13=py37_0
  - sacremoses=0.0.43=pyh9f0ad1d_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.6.2=py37h91f5cce_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py_0
  - sentry-sdk=0.17.3=pyh9f0ad1d_0
  - setuptools=49.6.0=py37_0
  - shortuuid=1.0.1=py37hc8dfbb8_2
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - smart_open=3.0.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - srsly=1.0.2=py37he6710b0_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorboardx=2.1=py_0
  - termcolor=1.1.0=py_2
  - terminado=0.9.1=py37hc8dfbb8_0
  - testpath=0.4.4=py_0
  - thinc=7.4.1=py37hfd86e86_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=pyh9f0ad1d_0
  - torchtext=0.6.0=py_1
  - torchvision=0.5.0=py37_cu100
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.59.0=pyhd3eb1b0_1
  - traitlets=5.0.4=py_1
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.24.3=py37_0
  - wandb=0.9.6=pyh9f0ad1d_0
  - wasabi=0.7.1=py_0
  - watchdog=0.10.3=py37hc8dfbb8_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.5.1=py37h7b6447c_0
  - zeromq=4.3.2=he1b5a44_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - annoy==1.17.0
    - antlr4-python3-runtime==4.8
    - astunparse==1.6.3
    - benepar==0.1.2
    - bertviz==1.1.0
    - cached-property==1.5.2
    - cython==0.29.21
    - dataclasses==0.6
    - datasets==1.9.0
    - dill==0.3.4
    - en-core-web-sm==2.3.1
    - fairseq==0.10.2
    - fastbpe==0.1.0
    - fasteners==0.16
    - fasttext==0.9.2
    - flatbuffers==1.12
    - fsspec==2021.7.0
    - gast==0.3.3
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - huggingface-hub==0.0.12
    - hydra-core==1.0.6
    - importlib-resources==5.1.2
    - keras-preprocessing==1.1.2
    - lz4==3.1.3
    - monotonic==1.5
    - moverscore==1.0.3
    - multiprocess==0.70.12.2
    - nlpaug==1.1.0
    - numpy==1.19.5
    - omegaconf==2.0.6
    - opt-einsum==3.3.0
    - packaging==21.0
    - pdfminer-six==20200517
    - pdfplumber==0.5.28
    - portalocker==2.0.0
    - pyarrow==4.0.1
    - pybind11==2.6.0
    - pycryptodome==3.10.1
    - pymagnitude==0.1.143
    - pytorch-warmup==0.0.4
    - pytreebank==0.2.7
    - sacrebleu==1.5.1
    - sentence-transformers==2.0.0
    - sentencepiece==0.1.91
    - sortedcontainers==2.4.0
    - spacy==2.3.2
    - tensorboard==2.4.0
    - tensorflow-estimator==2.4.0
    - tokenizers==0.8.1rc2
    - torch==0.4.1
    - transformers==3.1.0
    - typing==3.7.4.3
    - wand==0.6.7
    - wmd==1.3.2
    - wrapt==1.12.1
    - xxhash==2.0.0
